version: '2'

services:
    nginx:
        image: nginx
        env_file:
              - .env
        ports:
              - ${NGINX_PORT}:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/web

    php:
        build: docker/php-fpm
        env_file:
            - .env
        volumes:
            - .:/var/www:delegated
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini

    mysql:
        image: mysql:5.6
        env_file:
            - .env

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file:
            - .env
        ports:
            - ${PHPMYADMIN_PORT}:80
        depends_on:
            - mysql
