fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

valouleloup_issue:
    resource: "@ValouleloupIssueBundle/Resources/config/routing.yml"
    prefix:   /issue-bundle

app:
    resource: '@AppBundle/Controller/'
    type: annotation