hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

gitlab_login:
    path: /login/check-gitlab

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

valouleloup_issue:
    resource: "@ValouleloupIssueBundle/Resources/config/routing.yml"
    prefix:   /issue-bundle

app:
    resource: '@AppBundle/Controller/'
    type: annotation