# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\MyUser:
            algorithm: bcrypt

    providers:
        my_user:
            entity:
                class: AppBundle\Entity\MyUser
                property: email

    firewalls:
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/(login|register), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
